default_install_hook_types:
- pre-commit
- commit-msg
- post-checkout
- post-merge

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: ["--markdown-linebreak-ext=md"]

# linting
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.0
  hooks:
    - id: ruff
    - id: ruff-format

# static type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
  - id: mypy
    files: ^src/
    # additional_dependencies:

